// Code generated by MockGen. DO NOT EDIT.
// Source: ip_grpc.pb.go

// Package ipscannerapi is a generated GoMock package.
package ipscannerapi

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockIPServiceClient is a mock of IPServiceClient interface.
type MockIPServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPServiceClientMockRecorder
}

// MockIPServiceClientMockRecorder is the mock recorder for MockIPServiceClient.
type MockIPServiceClientMockRecorder struct {
	mock *MockIPServiceClient
}

// NewMockIPServiceClient creates a new mock instance.
func NewMockIPServiceClient(ctrl *gomock.Controller) *MockIPServiceClient {
	mock := &MockIPServiceClient{ctrl: ctrl}
	mock.recorder = &MockIPServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPServiceClient) EXPECT() *MockIPServiceClientMockRecorder {
	return m.recorder
}

// ScanIP mocks base method.
func (m *MockIPServiceClient) ScanIP(ctx context.Context, in *ScanIPRequest, opts ...grpc.CallOption) (*ScanIPResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanIP", varargs...)
	ret0, _ := ret[0].(*ScanIPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanIP indicates an expected call of ScanIP.
func (mr *MockIPServiceClientMockRecorder) ScanIP(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanIP", reflect.TypeOf((*MockIPServiceClient)(nil).ScanIP), varargs...)
}

// MockIPServiceServer is a mock of IPServiceServer interface.
type MockIPServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockIPServiceServerMockRecorder
}

// MockIPServiceServerMockRecorder is the mock recorder for MockIPServiceServer.
type MockIPServiceServerMockRecorder struct {
	mock *MockIPServiceServer
}

// NewMockIPServiceServer creates a new mock instance.
func NewMockIPServiceServer(ctrl *gomock.Controller) *MockIPServiceServer {
	mock := &MockIPServiceServer{ctrl: ctrl}
	mock.recorder = &MockIPServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPServiceServer) EXPECT() *MockIPServiceServerMockRecorder {
	return m.recorder
}

// ScanIP mocks base method.
func (m *MockIPServiceServer) ScanIP(arg0 context.Context, arg1 *ScanIPRequest) (*ScanIPResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanIP", arg0, arg1)
	ret0, _ := ret[0].(*ScanIPResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ScanIP indicates an expected call of ScanIP.
func (mr *MockIPServiceServerMockRecorder) ScanIP(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanIP", reflect.TypeOf((*MockIPServiceServer)(nil).ScanIP), arg0, arg1)
}

// mustEmbedUnimplementedIPServiceServer mocks base method.
func (m *MockIPServiceServer) mustEmbedUnimplementedIPServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIPServiceServer")
}

// mustEmbedUnimplementedIPServiceServer indicates an expected call of mustEmbedUnimplementedIPServiceServer.
func (mr *MockIPServiceServerMockRecorder) mustEmbedUnimplementedIPServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIPServiceServer", reflect.TypeOf((*MockIPServiceServer)(nil).mustEmbedUnimplementedIPServiceServer))
}

// MockUnsafeIPServiceServer is a mock of UnsafeIPServiceServer interface.
type MockUnsafeIPServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeIPServiceServerMockRecorder
}

// MockUnsafeIPServiceServerMockRecorder is the mock recorder for MockUnsafeIPServiceServer.
type MockUnsafeIPServiceServerMockRecorder struct {
	mock *MockUnsafeIPServiceServer
}

// NewMockUnsafeIPServiceServer creates a new mock instance.
func NewMockUnsafeIPServiceServer(ctrl *gomock.Controller) *MockUnsafeIPServiceServer {
	mock := &MockUnsafeIPServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeIPServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeIPServiceServer) EXPECT() *MockUnsafeIPServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedIPServiceServer mocks base method.
func (m *MockUnsafeIPServiceServer) mustEmbedUnimplementedIPServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedIPServiceServer")
}

// mustEmbedUnimplementedIPServiceServer indicates an expected call of mustEmbedUnimplementedIPServiceServer.
func (mr *MockUnsafeIPServiceServerMockRecorder) mustEmbedUnimplementedIPServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedIPServiceServer", reflect.TypeOf((*MockUnsafeIPServiceServer)(nil).mustEmbedUnimplementedIPServiceServer))
}
