// Code generated by protoc-gen-go-client-builder. DO NOT EDIT.
//
// Version: (devel)
//---------------------------------------------------

//go:generate mockgen -source=ip_grpc.pb.go -package=ipscannerapi -destination=ip_grpc.pb.mock.go

package ipscannerapi

import (
	"fmt"
	"net"

	gomock "github.com/golang/mock/gomock"
	"google.golang.org/grpc"
)

type MockClient struct {
	Client        *Client
	recorder      *MockClientMockRecorder
	MockIPService *MockIPServiceClient
}

type MockClientMockRecorder struct {
	*MockIPServiceClientMockRecorder
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mockClient := &MockClient{
		MockIPService: NewMockIPServiceClient(ctrl),
	}

	mockClient.recorder = &MockClientMockRecorder{
		MockIPServiceClientMockRecorder: mockClient.MockIPService.recorder,
	}

	mockClient.Client = &Client{
		conn:            nil,
		IPServiceClient: mockClient.MockIPService,
	}

	return mockClient
}

func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

type MockServer struct {
	IPService *MockIPServiceServer
	Server    *grpc.Server
	Listener  net.Listener
}

func (m *MockServer) Close() error {
	m.Server.GracefulStop()
	return m.Listener.Close()
}

func NewMockServer(ctrl *gomock.Controller, cfg *Config, opts ...grpc.ServerOption) (*MockServer, error) {
	s := &MockServer{
		Server:    grpc.NewServer(opts...),
		IPService: NewMockIPServiceServer(ctrl),
	}

	l, err := net.Listen("tcp", cfg.Host)
	if err != nil {
		return nil, fmt.Errorf("failed to listen tcp %s: %w", cfg.Host, err)
	}

	s.Listener = l
	RegisterIPServiceServer(s.Server, s.IPService)
	return s, nil
}
